databaseType = "PostgreSql"
name = "DevtoQADeploy"
id = "09aa01fe-5711-4c83-adf8-dd1b77e52b24"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[flyway]
mixed = true
outOfOrder = true
locations = [ "filesystem:migrations" ]
validateMigrationNaming = true
baselineVersion = "001_20240118140184"
baselineOnMigrate = true

  [flyway.check]
  majorTolerance = 0
