-- Script generated by Redgate Compare v1.18.3.12465
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test_flyway_chk2...';END$$;
CREATE TABLE main.test_flyway_chk2 (
    flyway character varying(50)
);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test_flyway_chk...';END$$;
CREATE TABLE main.test_flyway_chk (
    flyway character varying(50)
);

SET check_function_bodies = true;
