-- Script generated by Redgate Compare v1.18.3.12465
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test1...';END$$;
CREATE TABLE main.test1 (
    check1 character varying
);

SET check_function_bodies = true;
