-- Script generated by Redgate Compare v1.18.3.12465
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test_flyway_chk...';END$$;
CREATE TABLE main.test_flyway_chk (
    flyway numeric
);

SET check_function_bodies = true;
