-- Script generated by Redgate Compare v1.18.3.12465
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping main.test_flyway_chk...';END$$;
DROP TABLE main.test_flyway_chk;

SET check_function_bodies = true;
