-- Script generated by Redgate Compare v1.18.3.12465
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test3.check6...';END$$;
ALTER TABLE main.test3 ADD COLUMN check6 character varying;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating main.test1.check2...';END$$;
ALTER TABLE main.test1 ADD COLUMN check2 character varying;

SET check_function_bodies = true;
